# This is a basic workflow to help you get started with Actions

name: TestEnvironments

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  testResuable:
    uses: .github/workflows/deployTest.yml

  # This workflow contains a single job called "build"
  deployToDevLondon:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: Dev-London
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  # This workflow contains a single job called "build"
  deployDevQuincy:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: Dev-Quincy
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  # This workflow contains a single job called "build"
  deployDevVirginia:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: Dev-Virginia
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!





  # This workflow contains a single job called "build"
  deployToProdLondon:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: Prod-London
    needs: deployToDevLondon

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  # This workflow contains a single job called "build"
  deployProdQuincy:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: Prod-Quincy
    needs: deployDevQuincy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

  # This workflow contains a single job called "build"
  deployProdVirginia:
    # The type of runner that the job will run on
    runs-on: windows-latest
    environment: Prod-Virginia
    needs: deployDevVirginia

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!